# Generated by Django 3.0.8 on 2020-09-19 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_uncstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField(default=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.UncStudent')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.AppTeam')),
            ],
        ),
    ]
