# Generated by Django 3.0.8 on 2020-09-20 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20200919_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('left', models.IntegerField(default=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.UncStudent')),
            ],
        ),
    ]
