# Generated by Django 3.0.8 on 2020-09-20 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='due',
        ),
    ]
