# Generated by Django 3.0.8 on 2020-09-22 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_review_due'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teamwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.IntegerField(editable=False)),
                ('question_1', models.BooleanField(default=False)),
                ('question_2', models.BooleanField(default=False)),
                ('question_3', models.BooleanField(default=False)),
                ('notes', models.TextField(null=True)),
                ('student', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='course.UncStudent')),
                ('teammate', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='teammate', to='course.UncStudent')),
            ],
        ),
    ]
