# Generated by Django 3.0.8 on 2020-09-24 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_teamwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engineering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(editable=False, null=True)),
                ('requirement_labels', models.TextField(default='NONE')),
                ('requirement_1', models.BooleanField(default=False)),
                ('requirement_2', models.BooleanField(default=False)),
                ('requirement_3', models.BooleanField(default=False)),
                ('requirement_4', models.BooleanField(default=False)),
                ('requirement_5', models.BooleanField(default=False)),
                ('requirement_6', models.BooleanField(default=False)),
                ('requirement_7', models.BooleanField(default=False)),
                ('requirement_8', models.BooleanField(default=False)),
                ('requirement_9', models.BooleanField(default=False)),
                ('requirement_10', models.BooleanField(default=False)),
                ('requirement_11', models.BooleanField(default=False)),
                ('requirement_12', models.BooleanField(default=False)),
                ('requirement_13', models.BooleanField(default=False)),
                ('requirement_14', models.BooleanField(default=False)),
                ('requirement_15', models.BooleanField(default=False)),
                ('requirement_16', models.BooleanField(default=False)),
                ('notes_1', models.TextField(blank=True, null=True)),
                ('notes_2', models.TextField(blank=True, null=True)),
                ('notes_3', models.TextField(blank=True, null=True)),
                ('notes_4', models.TextField(blank=True, null=True)),
                ('notes_5', models.TextField(blank=True, null=True)),
                ('notes_6', models.TextField(blank=True, null=True)),
                ('notes_7', models.TextField(blank=True, null=True)),
                ('notes_8', models.TextField(blank=True, null=True)),
                ('notes_9', models.TextField(blank=True, null=True)),
                ('notes_10', models.TextField(blank=True, null=True)),
                ('notes_11', models.TextField(blank=True, null=True)),
                ('notes_12', models.TextField(blank=True, null=True)),
                ('notes_13', models.TextField(blank=True, null=True)),
                ('notes_14', models.TextField(blank=True, null=True)),
                ('notes_15', models.TextField(blank=True, null=True)),
                ('notes_16', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.IntegerField()),
                ('engineering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Engineering')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.AppTeam')),
            ],
        ),
    ]
