# Generated by Django 3.0.8 on 2020-09-26 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_engineering_projectmilestone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectMilestone',
        ),
    ]
