# Generated by Django 3.0.8 on 2020-09-26 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_delete_projectmilestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineering',
            name='milestone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='engineering',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.AppTeam'),
        ),
    ]
