# Generated by Django 3.0.8 on 2020-09-26 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20200926_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineering',
            name='milestone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='engineering',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.AppTeam'),
        ),
    ]
