# Generated by Django 3.0.8 on 2020-09-26 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_auto_20200926_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineering',
            name='requirement_labels',
        ),
    ]
