# Generated by Django 3.0.8 on 2020-09-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_remove_engineering_requirement_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineering',
            name='label_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='engineering',
            name='label_10',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='engineering',
            name='label_11',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='engineering',
            name='label_12',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='engineering',
            name='label_13',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='engineering',
            name='label_14',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='engineering',
            name='label_15',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='engineering',
            name='label_16',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='engineering',
            name='label_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='engineering',
            name='label_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='engineering',
            name='label_4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='engineering',
            name='label_5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='engineering',
            name='label_6',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='engineering',
            name='label_7',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='engineering',
            name='label_8',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='engineering',
            name='label_9',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
