# Generated by Django 3.0.8 on 2020-10-01 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_auto_20200926_1328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Engineering',
            new_name='Checklist',
        ),
    ]
